//! # xboard-core
//!
//! Shared business core for `xboard-client`. Holds the single implementation
//! of every non-UI concern:
//!
//! - [`api`]      — typed Xboard HTTP client (V1 + V2 surfaces)
//! - [`profile`]  — subscription text fetcher with ETag caching
//! - [`kernel`]   — [`kernel::KernelDriver`] trait + mihomo / xray drivers
//! - [`tunnel`]   — platform tunnel adapters (system proxy, VpnService, TUN)
//! - [`updater`]  — signed kernel + app self-update pipeline
//! - [`storage`]  — SQLite + secure key storage abstraction
//! - [`ipc`]      — UI ⇄ kernel transport (HTTP for mihomo, sockets for VPN)
//!
//! UI shells (Tauri, Android Compose) consume this crate through `Arc`-shared
//! handles; no business logic lives in either UI codebase.

#![deny(unsafe_op_in_unsafe_fn)]
#![warn(rust_2018_idioms, missing_debug_implementations)]

pub mod api;
pub mod error;
pub mod ffi;
pub mod ipc;
pub mod kernel;
pub mod profile;
pub mod storage;
pub mod tunnel;
pub mod updater;

pub use error::{Result, XboardError};
// Kernel re-exports — driver/manager/launcher trait surface that callers
// outside the workspace can use directly. `ConnectStage` / `ConnectionState`
// / `TunnelMode` are deliberately omitted: the FFI versions of those names
// (re-exported via `pub use ffi::*` below) are what UniFFI's scaffolding
// macro looks up at the crate root. Internal callers reach the kernel
// shapes via the qualified `crate::kernel::manager::*` path.
pub use kernel::{
    DirectLauncher, KernelDriver, KernelKind, KernelLauncher, KernelManager, LauncherError,
    MihomoDriver,
};

pub use api::CheckLoginResp;
#[cfg(any(target_os = "windows", target_os = "macos", target_os = "linux"))]
pub use storage::KeyringStore;

// UniFFI surface. `pub use ffi::*` lifts every interface / dictionary /
// enum / callback the UDL declares to the crate root, where the
// scaffolding macro below expects to find them.
pub use ffi::*;

// Pulls in the Rust scaffolding generated by `build.rs` from
// `src/ffi.udl`. Must come AFTER `pub use ffi::*` so the symbols the
// scaffolding references (Client, ConnectionManager, FfiError, …) are
// already visible at the crate root.
uniffi::include_scaffolding!("ffi");

/// Crate version (matches `Cargo.toml`).
///
/// Returns `String` (not `&'static str`) because the UniFFI `string` type
/// in `ffi.udl` lowers to an owned `String` on the FFI boundary — the
/// scaffolding macro can't borrow into the static segment of the cdylib.
pub fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// FFI-facing wrapper around [`profile::patch_singbox`]. Translates the
/// public `TunnelMode` enum to the internal one and re-raises errors as
/// `FfiError`. Lives at the crate root because UniFFI's `namespace`
/// section resolves free functions from there.
pub fn render_singbox_config(
    subscribe_yaml: String,
    external_controller: String,
    secret: String,
    mixed_port: u16,
    mode: ffi::TunnelMode,
) -> Result<String, ffi::FfiError> {
    let internal = match mode {
        ffi::TunnelMode::Tun => profile::TunnelMode::Tun,
        ffi::TunnelMode::SystemProxy => profile::TunnelMode::SystemProxy,
    };
    profile::patch_singbox(
        &subscribe_yaml,
        &external_controller,
        &secret,
        mixed_port,
        internal,
    )
    .map_err(ffi::FfiError::from)
}
