//! UniFFI build-time hook.
//!
//! Compiles `src/ffi.udl` into the Rust scaffolding that `lib.rs`'s
//! `uniffi::include_scaffolding!("ffi")` then pulls in. The scaffolding
//! exposes `extern "C"` symbols matching the IDL — Kotlin / Swift bindings
//! generated by `uniffi-bindgen` (run separately, see justfile) bind to
//! those symbols via JNI / FFI.
//!
//! UniFFI re-runs only when `src/ffi.udl` changes; manually edited
//! adapter code in `src/ffi/` triggers normal cargo recompiles via the
//! mod tree.

fn main() {
    uniffi::generate_scaffolding("src/ffi.udl").expect("uniffi scaffolding for src/ffi.udl");
}
